### ISSUE TITLE
Trip updates - zero delay causing Google error

### ISSUE THREAD

**Issue by kevinsmgov** [google/gtfs-realtime-bindings#16] opened 2016-02-29 17:27 UTC
When we first implemented our GTFS real time services, we rolled our own data model for our protobuf feed. We recently switched to using gtfs-realtime-bindings but we've run into an issue.

When we assign a zero value to Delay in Arrival (StopTimeEvent) for TripUpdates (i.e. the trip is on time) Google is interpreting it as no value and generating a warning report for our feed. A debug snapshot from Google shows:

```
stop_time_update {
      stop_sequence: 1
      arrival {

      }
    }
```

When what we're expecting to see is:

```
stop_time_update {
      stop_sequence: 1
      arrival {
        delay: 0
      }
    }
```

The feed works correctly for any other delay values, just not for zero.

Do you have any information on how on-time trips are supposed to be notated with the gtfs-realtime-bindings model?

@thekaveman

**Comment by magdalar** [comment] 2016-02-29 21:37
What language and environment are you working with?

**Comment by kevinsmgov** [comment] 2016-02-29 21:39
C# .NET

**Comment by magdalar** [comment] 2016-03-01 11:58
Could you provide an example of how you're setting the field, and how you're serializing the final message?

**Comment by magdalar** [comment] 2016-03-01 12:04
Actually, this looks relevant to your question: http://stackoverflow.com/questions/12295976/force-protobuf-net-to-serialize-all-default-values

**Comment by barbeau** [comment] 2019-03-01 10:45
@kevinsmgov Is this still an issue for you?  If so, could you please provide a link to your GTFS-rt feed?

**Comment by barbeau** [comment] 2019-03-01 11:06
Looks like this is a duplicate of https://github.com/google/gtfs-realtime-bindings/issues/32, so I'm closing this issue and we can continue the discussion in that thread.

**Closed by barbeau** 2019-03-01 11:06 UTC
Labels: bug

**Comment by kevinsmgov** [comment] 2019-03-04 14:30
> @kevinsmgov Is this still an issue for you? If so, could you please provide a link to your GTFS-rt feed?

About a week after we posted this, we switched back to our original home-grown protobuf code so it was no longer an issue for us. Can't answer as to whether the issue has been corrected in this repository or not.
