### ISSUE TITLE
MTA feed issue

### ISSUE THREAD

**Issue by zzolo** [google/gtfs-realtime-bindings#2] opened 2015-04-01 16:42 UTC
I am having intermittent issues with the MTA protobuf feed.  I am mostly just at a loss on how to debug and track down the issue.

The feed is here (with an MTA key; happy to share off list):
http://datamine.mta.info/mta_esi.php?feed_id=1&key=[[[MTA_API_KEY]]]

The error I get is the following.  It is intermittent and there does not seem to be any pattern as to when/why it happens, though it roughly happens every 5 reads.

```
/Users/zzolo/Codemta-project/node_modules/gtfs-realtime-bindings/node_modules/protobufjs/ProtoBuf.js:1987
                            throw(e);
                                  ^
RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint8 (native)
    at ByteBuffer.readVarint32 (/Users/zzolo/Codemta-project/node_modules/gtfs-realtime-bindings/node_modules/protobufjs/node_modules/bytebuffer/ByteBuffer.js:1123:25)
    at ProtoBuf.Reflect.Message.decode (/Users/zzolo/Codemta-project/node_modules/gtfs-realtime-bindings/node_modules/protobufjs/ProtoBuf.js:2111:38)
    at ProtoBuf.Reflect.Field.decode (/Users/zzolo/Codemta-project/node_modules/gtfs-realtime-bindings/node_modules/protobufjs/ProtoBuf.js:2594:46)
    at ProtoBuf.Reflect.Message.decode (/Users/zzolo/Codemta-project/node_modules/gtfs-realtime-bindings/node_modules/protobufjs/ProtoBuf.js:2139:51)
    at ProtoBuf.Reflect.Field.decode (/Users/zzolo/Codemta-project/node_modules/gtfs-realtime-bindings/node_modules/protobufjs/ProtoBuf.js:2594:46)
    at ProtoBuf.Reflect.Message.decode (/Users/zzolo/Codemta-project/node_modules/gtfs-realtime-bindings/node_modules/protobufjs/ProtoBuf.js:2137:51)
    at Function.Message.decode (/Users/zzolo/Codemta-project/node_modules/gtfs-realtime-bindings/node_modules/protobufjs/ProtoBuf.js:1982:41)
    at /Users/zzolo/Codemta-project/index.js:140:49
    at Array.forEach (native)
```

My code is essentially the same as the example here:
https://github.com/google/gtfs-realtime-bindings/tree/master/nodejs#example-code

The error appears at the line:
`var feed = GtfsRealtimeBindings.FeedMessage.decode(body);`

**Comment by bdferris** [comment] 2015-04-01 17:44
Hey @zzolo ;)

Any chance you could save the raw protobuf data to disk before you attempt to decode and share one of the corrupted payloads so we can take a closer look?

**Comment by zzolo** [comment] 2015-04-02 15:34
Hey Brian!  How's it going?  Thanks for the help and the great work.

Here is a zip of a few saved feeds (every 30 seconds) of the MTA GTFS RT feed.  The `.fail` are the ones that have that error.  Hopefully I saved them the right way.

https://dl.dropboxusercontent.com/u/18260842/mta-gtfs-rt-feed-examples.zip

**Comment by bdferris** [comment] 2015-04-03 02:47
I can confirm that your .fail feeds also fail to parse for me as well.  My guess is that the data is truncated in some way, especially since all the good feeds are averaging around 160k but the failing feeds both appear to be around 130k.

My guess is that this corruption is on the MTA side but I'm not sure.  Maybe I will try capturing a few feeds and see if I get similar results.

**Comment by zzolo** [comment] 2015-04-03 14:28
Thanks for looking into that.  That's the overall impression I got as well.

I did save that output via the `request` node module.  So, there's a possibility that the `request` module is screwing something up, but it would seem odd to be intermittent like that.

**Comment by bdferris** [comment] 2015-04-03 15:42
I've had a script running for the past 12 hours that pulls the MTA GTFS RT feed every 30 seconds with plain-old "curl" on the command line.  About 4% of the resulting feeds have been corrupted for me.  The frequency seems kind of random.  Sometimes I went close to 20 minutes without a bad read.  Other times, half my feeds were corrupted over a three minute window.

Either way, this seems like a problem on the MTA side of things, so I'm going to close this issue for now.

**Closed by bdferris** 2015-04-03 15:42 UTC

**Comment by zzolo** [comment] 2015-04-03 15:44
Thanks again for digging into that.  Maybe its some sort of rate-limiting thing, though it doesn't seem consistent enough for that.  Either way, I can get around it.

**Comment by bdferris** [comment] 2015-04-03 15:48
I'm not sure how they've implemented their feed.  Maybe they are just writing a file to disk periodically and sometimes you get unlucky and read the file as it's being updated?
